### PR TITLE
Add travis build file and badge

### PR DESCRIPTION
**Pull request by jbender**
Automate builds so that no bad code gets shipped (there are currently 4 failing specs).

Ideally this would be set up with automated deploys on tagged commits:
http://docs.travis-ci.com/user/deployment/rubygems/

### CODE REVIEW

**Comment by jbender** [comment]
ping @tkadauke

**Comment by tkadauke** [comment]
Great idea! Thanks!

**Comment by colinta** [comment]
Thanks for your help recently, @jbender.  I'm adding you as a collaborator, I hope you continue to help move this project forward! :smile: :+1:

**Comment by jbender** [comment]
@colinta glad to help out, hopefully we can make iOS dev as fast/easy as writing a Rails app

**Pull request merged**
