### PR TITLE
Add .to_json monkeypatches

### PR DESCRIPTION
**Pull request by jbender**
Adds `.to_json` to core classes, uses `NSJSONSerialization` for non-primitives.

### CODE REVIEW

**Comment by tkadauke** [comment]
I think now you need to rebase this for the merge to succeed. On first sight I guess it's the README.

Other than that it looks good.

**Comment by jbender** [comment]
@tkadauke Should be good to go

**Comment by jbender** [comment]
(don't forget to sign up for TravisCI.org, I can't sign up this repo as I'm not an owner of it)

**Comment by jbender** [comment]
bump @tkadauke

**Comment by tkadauke** [comment]
I can merge this for now, although I think one of the more active members should sign up for TravisCI.org (if not done already). @colinta? @clayallsopp?

**Comment by colinta** [comment]
I turned on TravisCI support, I forget if there's anything else to do.

**Comment by jbender** [comment]
Would recommend looking at http://docs.travis-ci.com/user/deployment/rubygems/

Basically just run `travis setup rubygems` and it'll be configured to automatically build and deploy tagged versions so you don't have to think about it in the future :fireworks:

**Comment by colinta** [comment]
Done!  Thanks, @jbender!

**Pull request merged**
